# Build and release ipinfo cli to PPA

name: Push to PPA
on: workflow_dispatch

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract CLI Name and Version
        run: echo "CLI_VERSION=3.1.2" >> $GITHUB_ENV

      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Install build dependencies
        run: sudo apt install devscripts debhelper dh-golang dput

      - name: Build source package
        run: debuild -us -uc -S -d

      - name: Sign source package
        run: |
          cd ./..
          debsign -k ${{ secrets.GPG_KEY_ID }} ipinfo_${{ env.CLI_VERSION }}.dsc ipinfo_${{ env.CLI_VERSION }}_source.changes

      - name: Push to Launchpad
        run: |
          cd ./..
          dput ppa:ipinfo/ppa ipinfo_${{ env.CLI_VERSION }}_source.changes
